DROP DATABASE IF EXISTS databaseB_dw;

CREATE DATABASE databaseB_dw;

USE databaseB_dw;

CREATE TABLE dim_time (
	TIME_ID INT AUTO_INCREMENT,
	YEAR INT NOT NULL,
	MONTH INT NOT NULL,
	SEASON ENUM('Winter', 'Spring', 'Summer', 'Autumn') NOT NULL,
	PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_location (
	LOCATION_ID INT AUTO_INCREMENT,
	REGION VARCHAR(255) NOT NULL,
	MUNICIPALITY VARCHAR(255) NOT NULL,
	PARISH VARCHAR(255) NOT NULL,
	PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE fact_energy_consumption (
	FACT_ID INT AUTO_INCREMENT,
	TIME_ID INT,
	LOCATION_ID INT,
	ENERGY_CONSUMPTION_KWH DECIMAL(10,2),
	PERCENTAGE_SMART_METERS DECIMAL(5,2),
	PRIMARY KEY (FACT_ID),
	FOREIGN KEY (TIME_ID) REFERENCES dim_time(TIME_ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES dim_location(LOCATION_ID)
);
